name: Parallal Test
on: push
jobs:
  test-search:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Search Test
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:search

      - name: Test Report-search Page
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: Mochaawsome HTML Report-Search Page
            path: cypress/reports    
    
  test-cart:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cart Test
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:cart
    
      - name: Test Report-cart Page
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochaawsome HTML Report-cart page
          path: cypress/reports 

