name: ProductSearch Test
on: push
jobs:
  test-search:
    runs-on: ubuntu-24.04
    steps:
      - name: Product Test
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:search
      - name: Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
              name: Mochaawsome HTML Report
              path: cypress/reports        