name: Smoke Test
on: push
jobs:
  test-smoke:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Smoke Test
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:smoke
      - name: Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: Mochaawsome HTML Report
            path: cypress/reports     